//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Web.MusicArtistsMgr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/MusicStore.Core")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicArtistsMgr.iArtist")]
    public interface iArtist {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iArtist/GetAllArtistList", ReplyAction="http://tempuri.org/iArtist/GetAllArtistListResponse")]
        System.Collections.Generic.List<MusicStore.Web.MusicArtistsMgr.Artist> GetAllArtistList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iArtist/GetAllArtistList", ReplyAction="http://tempuri.org/iArtist/GetAllArtistListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MusicStore.Web.MusicArtistsMgr.Artist>> GetAllArtistListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iArtistChannel : MusicStore.Web.MusicArtistsMgr.iArtist, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iArtistClient : System.ServiceModel.ClientBase<MusicStore.Web.MusicArtistsMgr.iArtist>, MusicStore.Web.MusicArtistsMgr.iArtist {
        
        public iArtistClient() {
        }
        
        public iArtistClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iArtistClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iArtistClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iArtistClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MusicStore.Web.MusicArtistsMgr.Artist> GetAllArtistList() {
            return base.Channel.GetAllArtistList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MusicStore.Web.MusicArtistsMgr.Artist>> GetAllArtistListAsync() {
            return base.Channel.GetAllArtistListAsync();
        }
    }
}
